### PR TITLE
[JENKINS-35329] Remove unused BC dependency

### PR DESCRIPTION
**Pull request by armfergom**
[JENKINS-35329](https://issues.jenkins-ci.org/browse/JENKINS-35329)

Also updated `.gitignore` to ignore eclipse related files.

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝

**Comment by alvarolobato** [comment]
🐝

**Comment by armfergom** [comment]
@reviewbybees  done

**Comment by recena** [comment]
@adamcin What do you thing about cutting a release?

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Pull request merged**
